version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment:
      - ALPHA_VANTAGE_API_KEY=your_alpha_vantage_api_key
    volumes:
      - .:/app